In [1]:
#import module

import pandas as pd

In [2]:
#서울시 어린이집, 유치원, 초등학교, 면적, 인구밀도 파일 불러오기

num_ele = pd.read_excel('num_elementary.xlsx', encoding='utf-8')
num_nursey = pd.read_excel('num_nursery.xlsx', encoding='utf-8')
num_kindergarten = pd.read_excel('num_kindergarten.xlsx', encoding='utf-8')
total_area = pd.read_excel('toal_area.xlsx', encoding='utf-8')
pop_ratio = pd.read_excel('서울시_인구밀도.xlsx', encoding='utf-8')

In [3]:
#num_ele.head()

In [4]:
#len(num_ele)

In [5]:
#num_nursey.head()

In [6]:
#len(num_nursey)

In [7]:
#num_kindergarten.head()

In [8]:
#len(num_kindergarten)

In [9]:
#total_area.head()

In [10]:
#len(total_area)

In [3]:
#서울시 어린이집, 유치원, 초등학교 개수 더하기

sum_facility = pd.concat([num_ele,num_nursey[['계 (개소)']],num_kindergarten[['개수']]], axis=1)
sum_facility['total'] = sum_facility.sum(axis=1)

In [4]:
#서울시 총 어린이 시설 개수와 인구밀도 데이터프레임 합치기

facility = pd.concat([sum_facility,pop_ratio[['인구밀도']]], axis=1)

In [5]:
#서울시 인구밀도 대비 어린이 시설 개수

facility['pop_ratio'] = pop_ratio['인구밀도']
facility['facility_ratio'] = facility['total'] / pop_ratio['인구밀도']

In [6]:
#데이터프레임 열 이름 바꾸기

del facility["인구밀도"]
facility.columns = ["region", "elementary","nursey", 'kindergarten', "total", "pop_ratio","per_facility"]

In [7]:
facility

     region  elementary  nursey  kindergarten  total  pop_ratio  per_facility
0    　　　종로구          13      77            17    107   0.568387    188.251984
1     　　　중구          12      69            14     95   1.070534     88.740763
2    　　　용산구          15     119            13    147   0.992345    148.133944
3    　　　성동구          21     179            30    230   1.918639    119.876616
4    　　　광진구          22     188            33    243   2.048034    118.650373
5   　　　동대문구          21     215            31    267   2.379082    112.228186
6    　　　중랑구          23     230            31    284   2.067466    137.366218
7    　　　성북구          29     267            49    345   1.989147    173.441152
8    　　　강북구          14     153            21    188   1.213342    154.943921
9    　　　도봉구          23     229            26    278   1.630055    170.546440
10   　　　노원구          42     405            66    513   1.752915    292.655339
11   　　　은평구          31     263            44    338   1.714072    197.191307
12  　　　서대문구          19     149            25    193   1.796020    107.459822
13   　　　마포구          22     209            24    255   1.725563    147.777838
14   　　　양천구          30     299            43    372   3.365045    110.548294
15   　　　강서구          36     409            56    501   1.622312    308.818543
16   　　　구로구          26     318            34    378   2.268850    166.604236
17   　　　금천구          18     157            19    194   1.626312    119.288332
18  　　　영등포구          23     248            39    310   1.514002    204.755390
19   　　　동작구          21     219            34    274   2.482754    110.361298
20   　　　관악구          22     251            33    306   1.341154    228.161645
21   　　　서초구          24     189            27    240   1.258618    190.685365
22   　　　강남구          33     201            38    272   1.682083    161.704225
23   　　　송파구          40     395            51    486   2.430392    199.967765
24   　　　강동구          27     260            32    319   2.013663    158.417733

In [33]:
#엑셀 파일로 저장하기

facility.to_excel("어린이 시설 비율.xlsx")